name: Run Financial Report

on:
  schedule:
    - cron: '0 10 * * 1-5'   # 11:00 CET
    - cron: '0 15 * * 1-5'   # 16:00 CET
    - cron: '0 19 * * 1-5'   # 20:00 CET
  workflow_dispatch:         # Still allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - run: pip install -r requirements.txt

      - name: Run Script 06
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python emailing.py
